name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      # Option 1: set the config file path. As many roles as you want!
      AWS_CONFIG_FILE: infra/aws_config
    steps:
    - uses: actions/checkout@v3

    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: 3
    
    - name: install boto3
      run: pip install boto3
    - name: install requests
      run: pip install requests
    
    - name: run
      run: python infra/Create_ec2.py ${{ secrets.AWS_KEY_ID }} ${{ secrets.AWS_SECRET_ACCESS_KEY }} ${{ secrets.AMI_ID }}  ${{ secrets.AWS_SECURITY_GROUP_ID }} ${{ secrets.JENKINS_ACCESS_TOKEN }}
      id: get_instances
