name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      # Option 1: set the config file path. As many roles as you want!
      AWS_CONFIG_FILE: infra/aws_config
    steps:
    - uses: actions/checkout@v3

    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: 3
    
    - name: install
      run: pip install boto3
    
    - name: run
      run: python infra/Create_ec2.py
    
    - name: Trigger pipeline
      run: curl http://http://34.238.83.188/:8080/job/test_build/build?token=test1234 --user shubham:11213508cf47a51366c8d2bceb33c718d2


