name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      # Option 1: set the config file path. As many roles as you want!
      AWS_CONFIG_FILE: infra/aws_config
    steps:
    - uses: actions/checkout@v3

    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: 3
    
    - name: install
      run: pip install boto3
    
    - name: run
      run: python infra/Create_ec2.py >> $GITHUB_OUTPUT
      id: get_instances
    
    - name: Trigger pipeline
      run: curl "http://${{steps.get_instances.outputs.public_ip}}:8080/job/build/build?token=test1234" --user shubham:11929ae8da72ed08fd123252027bfb0a4a


