name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-python@v2
      with:
          python-version: 3
    
    - name: install
      run: pip install boto3
    
    - name: run
      run: python infra/Create_ec2.py
    
    - name: Trigger pipeline
      run: curl http://54.87.70.255:8080/job/test_build/build?token=test1234 --user shubham:117f999f14443dbe7008faf83f89bcced7


